### ISSUE TITLE
Crash when trying to report unused imports

### ISSUE THREAD

**Issue by pmourlanne** [SublimeLinter/SublimeLinter-pyflakes#13]
Hello,

SublimeLinter-pyflakes is crashing on some of my files with the following stacktrace:

```python-traceback
SublimeLinter: ERROR: Linter crashed.

Traceback (most recent call last):
  File "/home/pmourlanne/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 87, in execute_lint_task
    errors = linter.lint(code, view_has_changed, settings) or []
  File "/home/pmourlanne/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 760, in lint
    return self.parse_output(output, virtual_view)
  File "/home/pmourlanne/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 781, in parse_output
    return self.parse_output_via_regex(output, virtual_view)
  File "/home/pmourlanne/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 801, in parse_output_via_regex
    error = self.process_match(m, virtual_view)
  File "/home/pmourlanne/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 885, in process_match
    line, start, end = self.reposition_match(m.line, col, m, vv)
  File "/home/pmourlanne/.config/sublime-text-3/Installed Packages/SublimeLinter-pyflakes.sublime-package/linter.py", line 39, in reposition_match
    return super().reposition_match(line, col, match, vv)
  File "/home/pmourlanne/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 921, in reposition_match
    if m.near:
AttributeError: 'NoneType' object has no attribute 'near'
```

I reproduced the issue with a minimal example. With these two files, the linter crashes when trying to ling the `test.py` file:
```python
# /tmp/test.py

from .file import (
    myfunction,
)
```

```python
# /tmp/file.py

def myfunction():
    pass
```

The linter does *not* crash with the following:
```python
# /tmp/test.py

from .file import myfunction
```

The issue appears to have appeared recently. I would guess this is caused by the changes in https://github.com/SublimeLinter/SublimeLinter-pyflakes/commit/e19cee4b47d296967286a7f065f363f1e64e58f6

Thanks in advance :)

Cheers,

Pierre

**Comment by kaste** [comment]
Hilarious

https://github.com/SublimeLinter/SublimeLinter-pyflakes/blob/b1654cff4f298b02247e0a288680a11a6b4cb7a5/linter.py#L21-L39

I reassign/overwrite `match` before calling `super` LOL

**Comment by kaste** [comment]
New release is coming... Takes up to an hour before Package Control will see it.

**Comment by pmourlanne** [comment]
Thank you for the reactivity!

**Comment by kaste** [comment]
Exercise for the reader, somehow still match the actually unused id

```
from .file import (
    myfunction,
)
```

Now we unfortunately mark the f of `from` I think.
